env_files = ["./.env"]

[config]
default_to_workspace = false


[tasks.dev]
command = "ssh"
args = [
    "-p",
    "443",
    "-R0:localhost:56010",
    "-L4300:localhost:4300",
    "-o",
    "StrictHostKeyChecking=no",
    "-o",
    "ServerAliveInterval=30",
    "wrr0fLztB5P@us.a.pinggy.io",
]

[tasks.noproxy]
script = """
export http_proxy=""
export https_proxy=""
"""

[tasks.setup-db]
command = "sqlx"
args = ["db", "setup", "--source", "crates/server/migrations"]

[tasks.run]
env = { http_proxy = "", https_proxy = "", RUST_LOG = "debug" }
command = "cargo"
args = ["run"]

[tasks.gather]
command = "python3"
args = ["gather_context.py", "context.md", "crates/server"]
