"use client";

import { useState, useRef, useEffect, useCallback } from "react";
import { getBuiltInType, BUILT_IN_TYPES, type BuiltInType } from "./TypeFieldInput";

const MAX_FONT_PX = 20;
const MIN_FONT_PX = 13;
const CATEGORY_PLACEHOLDER = "\u2039category\u203A"; // ‹category›
const CONTEXT_PLACEHOLDER = "\u2039context\u203A"; // ‹context›

interface CategoryForLineProps {
  category: string;
  onCategoryChange: (value: string) => void;
  forField: string;
  onForFieldChange: (value: string) => void;
  /** Auto-generated category text from options (when category is 'custom') */
  generatedCategoryText: string;
  disabled?: boolean;
  /** Delay before initial appearance, matching modal animation */
  initialDelay?: number;
}

export default function CategoryForLine({
  category,
  onCategoryChange,
  forField,
  onForFieldChange,
  generatedCategoryText,
  disabled = false,
  initialDelay = 0,
}: CategoryForLineProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const lineRef = useRef<HTMLSpanElement>(null);
  const categoryInputRef = useRef<HTMLInputElement>(null);
  const contextInputRef = useRef<HTMLInputElement>(null);
  const dropdownRef = useRef<HTMLDivElement>(null);

  const [categoryFocused, setCategoryFocused] = useState(false);
  const [contextFocused, setContextFocused] = useState(false);
  const [categoryEditText, setCategoryEditText] = useState("");
  const [highlightedIndex, setHighlightedIndex] = useState(-1);
  const [showDropdown, setShowDropdown] = useState(false);
  const [fontSizePx, setFontSizePx] = useState(MAX_FONT_PX);
  const [visible, setVisible] = useState(initialDelay === 0);
  // Tracks whether selectType/Enter already committed — prevents blur from re-committing
  const committedRef = useRef(false);
  // True when a built-in category hasn't been edited yet — first backspace clears it
  const categoryPristineRef = useRef(false);
  // Track whether field had a user value when focused — controls placeholder-as-minimum-width behavior
  const [categoryHadValueOnFocus, setCategoryHadValueOnFocus] = useState(false);
  const [contextHadValueOnFocus, setContextHadValueOnFocus] = useState(false);

  // Initial delay (wait for modal slide-up animation)
  useEffect(() => {
    if (initialDelay > 0) {
      const timer = setTimeout(() => setVisible(true), initialDelay);
      return () => clearTimeout(timer);
    }
  }, [initialDelay]);

  // Category display logic
  const builtIn = getBuiltInType(category);
  const categoryHasUserValue = category !== "custom";
  const categoryIsAutoGenerated = !categoryHasUserValue && !!generatedCategoryText;
  const showForAndContext = category !== "yes_no";

  let categoryDisplayValue: string;
  let categoryIsItalic = false;

  if (categoryFocused) {
    categoryDisplayValue = categoryEditText;
  } else if (categoryHasUserValue) {
    categoryDisplayValue = builtIn?.label || category;
  } else if (categoryIsAutoGenerated) {
    categoryDisplayValue = generatedCategoryText;
    categoryIsItalic = true;
  } else {
    categoryDisplayValue = "";
  }

  // "for" fading: only unfaded when both sides have content
  const categoryHasContent = categoryHasUserValue || categoryIsAutoGenerated;
  const contextHasContent = !!forField.trim();
  const forIsFaded = !(categoryHasContent && contextHasContent);

  // Dropdown filtering
  const filterText = categoryFocused ? categoryEditText : "";
  const filteredTypes = filterText
    ? BUILT_IN_TYPES.filter((t) =>
        t.label.toLowerCase().includes(filterText.toLowerCase())
      )
    : BUILT_IN_TYPES;

  // Font auto-sizing via binary search with smooth CSS transition
  const fitFont = useCallback(() => {
    const container = containerRef.current;
    const lineEl = lineRef.current;
    if (!container || !lineEl) return;

    // Capture current visual size (may be mid-transition)
    const currentVisual = parseFloat(getComputedStyle(lineEl).fontSize);

    // Disable transitions during measurement
    lineEl.style.transition = 'none';

    lineEl.style.fontSize = `${MAX_FONT_PX}px`;
    const containerWidth = container.clientWidth;

    // Use container.scrollWidth — lineEl is an inline span where scrollWidth is unreliable
    let target = MAX_FONT_PX;
    if (container.scrollWidth > containerWidth) {
      let lo = MIN_FONT_PX;
      let hi = MAX_FONT_PX;
      while (hi - lo > 0.5) {
        const mid = (lo + hi) / 2;
        lineEl.style.fontSize = `${mid}px`;
        if (container.scrollWidth > containerWidth) {
          hi = mid;
        } else {
          lo = mid;
        }
      }
      target = lo;
    }

    // Skip animation if already at target
    if (Math.abs(target - currentVisual) < 0.5) {
      lineEl.style.fontSize = `${target}px`;
      lineEl.style.transition = 'font-size 150ms ease';
      setFontSizePx(target);
      return;
    }

    // Animate: reset to current visual position, force reflow, then transition to target
    lineEl.style.fontSize = `${currentVisual}px`;
    void lineEl.offsetHeight; // Force reflow to establish starting point
    lineEl.style.transition = 'font-size 150ms ease';
    lineEl.style.fontSize = `${target}px`;
    setFontSizePx(target);
  }, []);

  // Refit on content or visibility changes
  useEffect(() => {
    if (visible) fitFont();
  }, [fitFont, visible, categoryDisplayValue, forField, generatedCategoryText, category]);

  // Refit on resize
  useEffect(() => {
    const observer = new ResizeObserver(fitFont);
    if (containerRef.current) observer.observe(containerRef.current);
    return () => observer.disconnect();
  }, [fitFont]);

  // Commit the current category edit text
  function commitCategory() {
    const trimmed = categoryEditText.trim();
    const match = BUILT_IN_TYPES.find(
      (t) => t.label.toLowerCase() === trimmed.toLowerCase()
    );
    if (match) {
      onCategoryChange(match.value);
    } else if (trimmed) {
      onCategoryChange(trimmed);
    } else {
      onCategoryChange("custom");
    }
    setCategoryEditText("");
  }

  const handleCategoryFocus = () => {
    setCategoryFocused(true);
    setCategoryHadValueOnFocus(categoryHasUserValue);
    if (categoryHasUserValue) {
      const label = builtIn?.label || category;
      setCategoryEditText(label);
      // Only mark pristine for built-in categories (backspace clears the whole value)
      categoryPristineRef.current = !!builtIn;
      // Put cursor at end
      requestAnimationFrame(() => {
        const input = categoryInputRef.current;
        if (input) input.setSelectionRange(label.length, label.length);
      });
    } else {
      // Auto-generated text disappears in favor of placeholder
      setCategoryEditText("");
      categoryPristineRef.current = false;
    }
    setShowDropdown(true);
    setHighlightedIndex(-1);
  };

  const handleCategoryBlur = (e: React.FocusEvent) => {
    // Don't close if focus moves to the dropdown
    if (dropdownRef.current?.contains(e.relatedTarget as Node)) return;
    // If selectType or Enter already committed, skip re-commit
    if (committedRef.current) {
      committedRef.current = false;
    } else {
      commitCategory();
    }
    setCategoryFocused(false);
    setShowDropdown(false);
  };

  const handleCategoryInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setCategoryEditText(e.target.value);
    categoryPristineRef.current = false;
    setHighlightedIndex(-1);
    if (!showDropdown) setShowDropdown(true);
  };

  const selectType = (type: BuiltInType) => {
    onCategoryChange(type.value);
    setCategoryEditText("");
    setCategoryFocused(false);
    setShowDropdown(false);
    committedRef.current = true;
    categoryInputRef.current?.blur();
  };

  const handleCategoryKeyDown = (e: React.KeyboardEvent) => {
    // First backspace on a pristine pre-populated value clears the whole field
    if (e.key === "Backspace" && categoryPristineRef.current) {
      e.preventDefault();
      setCategoryEditText("");
      categoryPristineRef.current = false;
      return;
    }
    if (e.key === "ArrowDown") {
      e.preventDefault();
      setHighlightedIndex((prev) =>
        prev < filteredTypes.length - 1 ? prev + 1 : prev
      );
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      setHighlightedIndex((prev) => (prev > 0 ? prev - 1 : -1));
    } else if (e.key === "Enter") {
      e.preventDefault();
      if (highlightedIndex >= 0 && highlightedIndex < filteredTypes.length) {
        selectType(filteredTypes[highlightedIndex]);
      } else {
        commitCategory();
        setCategoryFocused(false);
        setShowDropdown(false);
        committedRef.current = true;
        contextInputRef.current?.focus();
      }
    } else if (e.key === "Escape") {
      setCategoryEditText("");
      setCategoryFocused(false);
      setShowDropdown(false);
      categoryInputRef.current?.blur();
    }
  };

  // Scroll highlighted dropdown item into view
  useEffect(() => {
    if (highlightedIndex >= 0 && dropdownRef.current) {
      const items = dropdownRef.current.children;
      if (items[highlightedIndex]) {
        (items[highlightedIndex] as HTMLElement).scrollIntoView({ block: "nearest" });
      }
    }
  }, [highlightedIndex]);

  if (!visible) {
    return <div style={{ minHeight: `${MAX_FONT_PX + 8}px` }} />;
  }

  // Mirror text controls the width of the inline-block sizer span.
  // When the field was empty on focus, the placeholder width is the minimum.
  // When the field had custom text on focus, width tracks the text exactly.
  function mirrorText(
    isFocused: boolean,
    hadValueOnFocus: boolean,
    displayValue: string,
    placeholder: string,
  ): string {
    if (isFocused && hadValueOnFocus) return displayValue || "\u00A0";
    if (isFocused && displayValue.length < placeholder.length) return placeholder;
    return displayValue || placeholder;
  }

  const categoryMirrorText = mirrorText(
    categoryFocused, categoryHadValueOnFocus, categoryDisplayValue, CATEGORY_PLACEHOLDER,
  );
  const contextMirrorText = mirrorText(
    contextFocused, contextHadValueOnFocus, forField, CONTEXT_PLACEHOLDER,
  );

  // Suppress placeholder text while editing a field that started with content
  const hideCategoryPlaceholder = categoryFocused && categoryHadValueOnFocus;
  const hideContextPlaceholder = contextFocused && contextHadValueOnFocus;

  return (
    <div className="relative">
      <div
        ref={containerRef}
        className="text-center overflow-hidden whitespace-nowrap"
        style={{ minHeight: `${MAX_FONT_PX + 8}px` }}
      >
        <span
          ref={lineRef}
          className="font-bold"
          style={{
            fontSize: `${fontSizePx}px`,
            fontFamily: "'M PLUS 1 Code', monospace",
            transition: 'font-size 150ms ease',
          }}
        >
          {/* Category input with mirror sizer */}
          <span className="relative inline-block align-baseline px-px">
            <span
              className="whitespace-pre"
              style={{
                visibility: "hidden",
                fontStyle: categoryIsItalic ? "italic" : "normal",
              }}
              aria-hidden="true"
            >
              {categoryMirrorText}
            </span>
            <input
              ref={categoryInputRef}
              type="text"
              value={categoryDisplayValue}
              placeholder={hideCategoryPlaceholder ? "" : CATEGORY_PLACEHOLDER}
              onChange={handleCategoryInputChange}
              onFocus={handleCategoryFocus}
              onBlur={handleCategoryBlur}
              onKeyDown={handleCategoryKeyDown}
              disabled={disabled}
              aria-label="Category"
              role="combobox"
              aria-expanded={showDropdown}
              aria-autocomplete="list"
              className={`absolute inset-0 w-full bg-transparent border-none outline-none p-0 m-0
                ${categoryIsItalic ? "italic" : ""}
                ${categoryDisplayValue ? "text-blue-600 dark:text-blue-400" : ""}
                placeholder:text-gray-400 dark:placeholder:text-gray-500`}
              style={{
                fontSize: "inherit",
                fontFamily: "inherit",
                fontWeight: "inherit",
                caretColor: "#2563eb",
              }}
            />
          </span>

          {/* "for" connector and context — hidden for yes_no */}
          {showForAndContext && (
            <>
              <span
                className={
                  forIsFaded
                    ? "text-gray-400 dark:text-gray-500"
                    : "text-blue-600 dark:text-blue-400"
                }
              >
                {" for "}
              </span>

              {/* Context input with mirror sizer */}
              <span className="relative inline-block align-baseline px-px">
                <span
                  className="whitespace-pre"
                  style={{ visibility: "hidden" }}
                  aria-hidden="true"
                >
                  {contextMirrorText}
                </span>
                <input
                  ref={contextInputRef}
                  type="text"
                  value={forField}
                  placeholder={hideContextPlaceholder ? "" : CONTEXT_PLACEHOLDER}
                  onChange={(e) => onForFieldChange(e.target.value)}
                  onFocus={() => {
                    setContextFocused(true);
                    setContextHadValueOnFocus(!!forField.trim());
                  }}
                  onBlur={() => {
                    setContextFocused(false);
                    const trimmed = forField.trim();
                    if (trimmed !== forField) onForFieldChange(trimmed);
                  }}
                  disabled={disabled}
                  aria-label="Context"
                  className={`absolute inset-0 w-full bg-transparent border-none outline-none p-0 m-0
                    ${forField ? "text-blue-600 dark:text-blue-400" : ""}
                    placeholder:text-gray-400 dark:placeholder:text-gray-500`}
                  style={{
                    fontSize: "inherit",
                    fontFamily: "inherit",
                    fontWeight: "inherit",
                    caretColor: "#2563eb",
                  }}
                />
              </span>
            </>
          )}
        </span>
      </div>

      {/* Built-in types dropdown */}
      {showDropdown && filteredTypes.length > 0 && (
        <div
          ref={dropdownRef}
          role="listbox"
          className="absolute left-1/2 -translate-x-1/2 top-full mt-1 w-56 z-50 bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded-md shadow-lg max-h-48 overflow-y-auto"
        >
          {filteredTypes.map((type, index) => (
            <button
              key={type.value}
              type="button"
              role="option"
              aria-selected={category === type.value}
              onMouseDown={(e) => {
                e.preventDefault();
                selectType(type);
              }}
              onMouseEnter={() => setHighlightedIndex(index)}
              className={`w-full text-left px-3 py-2 text-sm flex items-center gap-2 ${
                highlightedIndex === index
                  ? "bg-blue-50 dark:bg-blue-900/30"
                  : "hover:bg-gray-50 dark:hover:bg-gray-700/50"
              } ${
                category === type.value
                  ? "text-blue-600 dark:text-blue-400 font-medium"
                  : "text-gray-900 dark:text-white"
              }`}
            >
              <span className="text-base">{type.icon}</span>
              <span>{type.label}</span>
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
