"""AI-powered poll suggestions: predict the next polls a user will create in a
group, tailored per (user, group), generated by an LLM from the group's + the
user's poll history.

Flow:
  • On poll-create (non-explore group): `create_poll` schedules
    `refresh_poll_suggestions(creator_user_id, group_id)` as a BackgroundTask.
  • On read (`GET /api/users/me/poll-suggestions`): return the cached row; if
    missing/stale, schedule a background refresh so the NEXT open is ready.
  • The FE re-derives each suggestion's title from its fields and re-ranks /
    filters the list in real time with the on-device embedding model.

Each suggestion is a STRUCTURED draft object — NOT a title:
    {category, title?, options?, context?}
The app auto-generates the displayed title from the fields (same as every poll),
so the LLM only emits fields. Everything is validated DETERMINISTICALLY here and
in the FE before it's shown, so a hallucinated/malformed suggestion is dropped.

The LLM call goes through services/llm_client (the shared Ollama-compatible
client), so dev/canary/prod all work with the existing variant-LLM wiring.
"""
from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone

from database import get_db
from services import llm_client

log = logging.getLogger("poll_suggest")

# Cap the list the LLM is asked for + the list we store/return.
MAX_SUGGESTIONS = 6
# How many recent polls to feed from each source, and the total char budget for
# the history block (keeps us well within a small local model's context window).
_GROUP_HISTORY_LIMIT = 40
_USER_HISTORY_LIMIT = 40
_HISTORY_CHAR_BUDGET = 5000
# A cached row older than this is regenerated in the background on read (poll
# creation refreshes it too, so active groups stay fresh without this firing).
_REFRESH_AFTER = timedelta(hours=12)

# Categories the LLM may suggest. Excludes `showtime` (needs a live cinema
# catalog) — every other creatable category opens a prefilled, ready-to-submit
# form. `time` is included: it opens the scheduling form seeded with the context.
SUGGESTABLE_CATEGORIES: frozenset[str] = frozenset(
    {"yes_no", "restaurant", "location", "movie", "video_game", "time", "limited_supply", "custom"}
)
# Categories whose `title` IS the poll (the typed prompt / item name).
_TITLE_REQUIRED = frozenset({"yes_no", "limited_supply"})
# Categories that can carry a fixed ballot-option list.
_OPTIONS_OK = frozenset({"restaurant", "location", "movie", "video_game", "custom"})

# Normalize loose category spellings the model might emit.
_CATEGORY_ALIASES: dict[str, str] = {
    "yes/no": "yes_no",
    "yesno": "yes_no",
    "yes-no": "yes_no",
    "videogame": "video_game",
    "video game": "video_game",
    "games": "video_game",
    "game": "video_game",
    "place": "location",
    "places": "location",
    "venue": "location",
    "food": "restaurant",
    "dining": "restaurant",
    "schedule": "time",
    "when": "time",
    "limited": "limited_supply",
    "limited supply": "limited_supply",
}

_CATEGORY_LABELS: dict[str, str] = {
    "yes_no": "Yes/No",
    "restaurant": "Restaurant",
    "location": "Place",
    "movie": "Movie",
    "video_game": "Video Game",
    "time": "Time",
    "limited_supply": "Limited Supply",
    "custom": "Custom",
}

_TITLE_MAX = 100
_OPTION_MAX = 80
_CONTEXT_MAX = 60
_MAX_OPTIONS = 8


@dataclass
class HistoryContext:
    group_lines: list[str] = field(default_factory=list)
    user_lines: list[str] = field(default_factory=list)
    existing_signatures: set[str] = field(default_factory=set)


@dataclass
class CachedSuggestions:
    suggestions: list[dict]
    generated_at: datetime


# ── History gathering ─────────────────────────────────────────────────────────


def _label(category: str | None) -> str:
    if not category:
        return "Poll"
    return _CATEGORY_LABELS.get(category, category.replace("_", " ").title())


def _poll_line(row: dict) -> str:
    """A compact one-line description of a past poll for the prompt."""
    label = _label(row.get("category"))
    qtype = row.get("question_type")
    if qtype == "time":
        label = "Time"
    elif qtype == "limited_supply":
        label = "Limited Supply"
    elif qtype == "yes_no":
        label = "Yes/No"
    title = (row.get("title") or "").strip()
    details = (row.get("details") or "").strip()
    # For yes_no / limited_supply the per-question `details` IS the real prompt /
    # item (the generic title is often just "Question?"), so prefer it; for other
    # types the title is the meaningful auto-title and details is the "for X".
    if qtype in ("yes_no", "limited_supply"):
        subject = details or title or "(untitled)"
    else:
        subject = title or details or "(untitled)"
    line = f'- [{label}] "{subject[:80]}"'
    opts = row.get("options")
    if isinstance(opts, list) and opts:
        clean = [str(o).strip() for o in opts if str(o).strip()][:6]
        if clean:
            line += " options: " + ", ".join(clean)
    return line


def _signature(category: str | None, title: str, options: list[str], context: str) -> str:
    """Normalized identity for dedup: same category + options + title + context."""
    opt_sig = "|".join(sorted(o.strip().lower() for o in options if o.strip()))
    return "::".join(
        [
            (category or "").strip().lower(),
            title.strip().lower(),
            context.strip().lower(),
            opt_sig,
        ]
    )


def _options_signature(category: str | None, options: list[str]) -> str | None:
    """A SECONDARY dedup key on (category + sorted options), ignoring context, so
    a suggestion that echoes an existing poll's option list is dropped even when
    the LLM attached a different/empty context (the common echo failure)."""
    opts = "|".join(sorted(o.strip().lower() for o in options if o.strip()))
    if not opts:
        return None
    return f"opts::{(category or '').strip().lower()}::{opts}"


def _signatures_for(category: str | None, title: str, options: list[str], context: str) -> list[str]:
    """The full signature plus the options-only signature (when present)."""
    sigs = [_signature(category, title, options, context)]
    opt_sig = _options_signature(category, options)
    if opt_sig:
        sigs.append(opt_sig)
    return sigs


def _row_signatures(row: dict) -> list[str]:
    opts = row.get("options")
    opt_list = [str(o) for o in opts] if isinstance(opts, list) else []
    qtype = row.get("question_type")
    category = "time" if qtype == "time" else (row.get("category") or "custom")
    return _signatures_for(
        category,
        (row.get("title") or "").strip(),
        opt_list,
        (row.get("details") or "").strip(),
    )


def gather_history(conn, user_id: str, group_id: str) -> HistoryContext | None:
    """Pull the group's recent polls + the user's recent polls (across their
    non-explore groups) into a compact prompt context. Returns None when the
    group is an explore group (suggestions are a normal-group feature) or inputs
    are missing."""
    if not user_id or not group_id:
        return None

    privacy_row = conn.execute(
        "SELECT privacy FROM groups WHERE id = %(gid)s", {"gid": group_id}
    ).fetchone()
    if not privacy_row or privacy_row.get("privacy") == "explore":
        return None

    ctx = HistoryContext()

    group_rows = conn.execute(
        """
        SELECT q.title, q.question_type, q.category, q.options, q.details
          FROM questions q
          JOIN polls p ON q.poll_id = p.id
         WHERE p.group_id = %(gid)s
         ORDER BY p.created_at DESC, q.question_index ASC
         LIMIT %(lim)s
        """,
        {"gid": group_id, "lim": _GROUP_HISTORY_LIMIT},
    ).fetchall()

    user_rows = conn.execute(
        """
        SELECT q.title, q.question_type, q.category, q.options, q.details
          FROM questions q
          JOIN polls p ON q.poll_id = p.id
          JOIN groups g ON p.group_id = g.id
         WHERE p.creator_user_id = %(uid)s
           AND g.privacy <> 'explore'
         ORDER BY p.created_at DESC
         LIMIT %(lim)s
        """,
        {"uid": user_id, "lim": _USER_HISTORY_LIMIT},
    ).fetchall()

    for r in group_rows:
        ctx.group_lines.append(_poll_line(r))
        ctx.existing_signatures.update(_row_signatures(r))
    for r in user_rows:
        ctx.user_lines.append(_poll_line(r))
        ctx.existing_signatures.update(_row_signatures(r))

    return ctx


# ── Prompt + generation ───────────────────────────────────────────────────────

_SYSTEM_PROMPT = (
    "You are the suggestion engine for WhoeverWants, a group decision-making "
    "app. People create POLLS to decide things together. Predict the NEXT polls "
    "THIS user is likely to create in THIS group, from the group's recent polls "
    "and the user's own poll history.\n\n"
    "A poll is built from STRUCTURED FIELDS; the app auto-generates the displayed "
    "title from those fields, so you output ONLY the fields.\n\n"
    "Output ONLY a JSON array (no prose, no markdown fences) of 4 to "
    f"{MAX_SUGGESTIONS} objects, each:\n"
    '{\n'
    '  "category": one of [yes_no, restaurant, location, movie, video_game, time, limited_supply, custom],\n'
    '  "title": string,    // REQUIRED for yes_no (the yes/no question, ending in "?") and limited_supply (what is being claimed). Omit for others.\n'
    '  "options": [string], // OPTIONAL 2-6 SPECIFIC named choices for restaurant/location/movie/video_game/custom. Omit to let the group suggest options.\n'
    '  "context": string    // OPTIONAL short real subject the poll is "for" (e.g. "Friday dinner"). Under 40 characters.\n'
    "}\n\n"
    "CATEGORY MEANINGS:\n"
    "- yes_no: one yes-or-no decision. title = the question.\n"
    "- restaurant: pick a place to eat. options = real restaurant names.\n"
    "- location: pick a place/venue (not food).\n"
    "- movie: pick a movie to watch. options = real movie titles.\n"
    "- video_game: pick a game to play. options = real game titles.\n"
    "- time: schedule when to meet. context = what the event is.\n"
    "- limited_supply: first-come claim for limited spots/items. title = what's claimed.\n"
    "- custom: any other choice; options = the choices, context = the subject.\n\n"
    "RULES:\n"
    f"- You MUST return at least 4 suggestions (up to {MAX_SUGGESTIONS}). LEAD with the group's + user's "
    "dominant decision types: MOST suggestions should match what they do most "
    "often, then add 1-2 natural adjacent ideas. A foodie group → mostly "
    "food/place/time; a work team → mostly yes/no calls + scheduling; a gaming "
    "group → mostly games + game nights. It is GOOD to suggest several polls of "
    "the SAME kind — do NOT just output one of every category.\n"
    "- Predict what comes NEXT. NEVER repeat, rephrase, or reuse the title, "
    "options, or subject of a poll already listed.\n"
    "- options must be SPECIFIC, real, named choices that fit this group (actual "
    "restaurant / movie / game names like \"Chipotle\", \"Dune: Part Two\", "
    '"Mario Kart 8") — NEVER generic words, genres, or filler like "Action, '
    'Comedy, Drama", "Sushi Place", "Italian Restaurant", "Pizzeria Pizza", or '
    '"Option 1". Do NOT lightly reword an existing poll\'s options. If you cannot '
    "name 2+ specific real options that fit, OMIT options and let the group "
    "suggest them — an omitted-options poll is better than a generic one.\n"
    "- context is the short real subject this poll is for; leave it out rather "
    "than inventing an unrelated one. Do not pair a context with an unrelated "
    "category.\n"
    "- Keep everything natural and concise, the way a real person types.\n"
    "- Output STRICTLY the JSON array and nothing else.\n\n"
    "EXAMPLE (illustrative only — base YOUR output on the history below; never "
    "copy these):\n"
    "If the history were a book club that picks books + schedules meetings, a good "
    "output is:\n"
    '[{"category":"custom","context":"next book pick","options":["Tomorrow, and '
    'Tomorrow, and Tomorrow","The Covenant of Water","Demon Copperhead"]},'
    '{"category":"time","context":"book club meeting"},'
    '{"category":"yes_no","title":"Should we switch to meeting monthly?"},'
    '{"category":"restaurant","context":"dinner after book club"},'
    '{"category":"location","context":"next meeting spot"}]\n'
    "Note it leads with the group's dominant type (book picks), names SPECIFIC "
    "real options there, and OMITS options on the rest rather than inventing "
    "generic ones."
)


def _build_user_message(ctx: HistoryContext) -> str:
    def block(lines: list[str]) -> str:
        return "\n".join(lines) if lines else "(none yet)"

    group_block = block(ctx.group_lines)
    user_block = block(ctx.user_lines)
    # Trim to the char budget, dropping oldest (the lists are newest-first, so
    # truncate the TAIL).
    combined = len(group_block) + len(user_block)
    if combined > _HISTORY_CHAR_BUDGET and ctx.user_lines:
        keep = max(5, _USER_HISTORY_LIMIT // 2)
        user_block = block(ctx.user_lines[:keep])
    return (
        "GROUP'S RECENT POLLS:\n"
        f"{group_block}\n\n"
        "THIS USER'S RECENT POLLS (across their groups):\n"
        f"{user_block}\n\n"
        f"Suggest 4 to {MAX_SUGGESTIONS} polls this user might create next in this "
        "group, leading with their dominant decision types. Output only the JSON array."
    )


def _extract_json_array(content: str) -> list:
    """Pull a JSON array out of the model's reply, tolerating fences/prose."""
    content = content.strip()
    fenced = re.search(r"```(?:json)?\s*(.+?)```", content, re.DOTALL)
    if fenced:
        content = fenced.group(1).strip()
    try:
        parsed = json.loads(content)
        if isinstance(parsed, list):
            return parsed
        if isinstance(parsed, dict):
            # Some models wrap the array, e.g. {"suggestions": [...]}.
            for v in parsed.values():
                if isinstance(v, list):
                    return v
    except (ValueError, TypeError):
        pass
    m = re.search(r"\[.*\]", content, re.DOTALL)
    if m:
        try:
            parsed = json.loads(m.group(0))
            if isinstance(parsed, list):
                return parsed
        except (ValueError, TypeError):
            pass
    return []


def _clean_str(value, limit: int) -> str:
    if not isinstance(value, str):
        return ""
    return " ".join(value.split()).strip()[:limit].strip()


def validate_suggestion(obj) -> dict | None:
    """Deterministically validate + normalize ONE raw LLM suggestion object into
    the stored/wire shape `{category, title?, options?, context?}`, or None when
    it's unusable. This is the server-side filter; the FE mirrors the shape."""
    if not isinstance(obj, dict):
        return None
    raw_cat = _clean_str(obj.get("category"), 40).lower()
    category = _CATEGORY_ALIASES.get(raw_cat, raw_cat)
    if category not in SUGGESTABLE_CATEGORIES:
        return None

    title = _clean_str(obj.get("title"), _TITLE_MAX)
    context = _clean_str(obj.get("context"), _CONTEXT_MAX)

    options: list[str] = []
    raw_opts = obj.get("options")
    if category in _OPTIONS_OK and isinstance(raw_opts, list):
        seen: set[str] = set()
        for o in raw_opts:
            label = _clean_str(o, _OPTION_MAX)
            key = label.lower()
            if label and key not in seen:
                seen.add(key)
                options.append(label)
            if len(options) >= _MAX_OPTIONS:
                break
        # A fixed-option poll needs >= 2; otherwise treat as suggestion-collection.
        if len(options) < 2:
            options = []

    if category in _TITLE_REQUIRED and not title:
        return None
    # For non-title categories, a stray title is noise — drop it (the title is
    # auto-generated from category + context + options).
    if category not in _TITLE_REQUIRED:
        title = ""

    out: dict = {"category": category}
    if title:
        out["title"] = title
    if options:
        out["options"] = options
    if context:
        out["context"] = context
    return out


def filter_and_dedup(raw: list, existing: set[str]) -> list[dict]:
    """Validate every raw suggestion, drop duplicates (of each other AND of
    existing polls), cap to MAX_SUGGESTIONS."""
    out: list[dict] = []
    seen = set(existing)
    for obj in raw:
        cleaned = validate_suggestion(obj)
        if not cleaned:
            continue
        sigs = _signatures_for(
            cleaned.get("category"),
            cleaned.get("title", ""),
            cleaned.get("options", []),
            cleaned.get("context", ""),
        )
        if any(s in seen for s in sigs):
            continue
        seen.update(sigs)
        out.append(cleaned)
        if len(out) >= MAX_SUGGESTIONS:
            break
    return out


def generate_from_history(ctx: HistoryContext) -> list[dict]:
    """Build the prompt, call the LLM, validate + dedup. No DB access — safe to
    call without holding a connection (the chat round-trip is slow)."""
    if not llm_client.is_configured():
        return []
    content = llm_client.chat(
        _SYSTEM_PROMPT,
        _build_user_message(ctx),
        model=llm_client.suggest_model(),
        temperature=0.8,
        timeout=llm_client.suggest_timeout(),
    )
    if not content:
        return []
    raw = _extract_json_array(content)
    return filter_and_dedup(raw, ctx.existing_signatures)


# ── Cache read/write ──────────────────────────────────────────────────────────


def store_suggestions(conn, user_id: str, group_id: str, suggestions: list[dict]) -> None:
    conn.execute(
        """
        INSERT INTO poll_suggestions (user_id, group_id, suggestions, generated_at)
        VALUES (%(uid)s, %(gid)s, %(sugg)s, NOW())
        ON CONFLICT (user_id, group_id)
        DO UPDATE SET suggestions = EXCLUDED.suggestions, generated_at = NOW()
        """,
        {"uid": user_id, "gid": group_id, "sugg": json.dumps(suggestions)},
    )


def load_cached_suggestions(conn, user_id: str, group_id: str) -> CachedSuggestions | None:
    if not user_id or not group_id:
        return None
    row = conn.execute(
        "SELECT suggestions, generated_at FROM poll_suggestions "
        "WHERE user_id = %(uid)s AND group_id = %(gid)s",
        {"uid": user_id, "gid": group_id},
    ).fetchone()
    if not row:
        return None
    sugg = row.get("suggestions")
    if isinstance(sugg, str):
        try:
            sugg = json.loads(sugg)
        except (ValueError, TypeError):
            sugg = []
    if not isinstance(sugg, list):
        sugg = []
    return CachedSuggestions(suggestions=sugg, generated_at=row["generated_at"])


def is_stale(cached: CachedSuggestions | None, now: datetime | None = None) -> bool:
    """True when there's no cache row or it's older than _REFRESH_AFTER — the
    read path schedules a background regen in that case."""
    if cached is None:
        return True
    now = now or datetime.now(timezone.utc)
    generated = cached.generated_at
    if generated.tzinfo is None:
        generated = generated.replace(tzinfo=timezone.utc)
    return now - generated > _REFRESH_AFTER


# ── Background refresh (decoupled own-transaction, like record_poll_categories) ──


def refresh_poll_suggestions(user_id: str | None, group_id: str | None) -> None:
    """Regenerate + cache suggestions for (user, group). Runs as a BackgroundTask
    on poll-create and on a stale/missing read. Opens its OWN connections so the
    slow LLM call never holds a pooled connection; logs + swallows failures so a
    generation hiccup can't surface to the user."""
    if not user_id or not group_id or not llm_client.is_configured():
        return
    try:
        with get_db() as conn:
            ctx = gather_history(conn, user_id, group_id)
        if ctx is None:
            return
        suggestions = generate_from_history(ctx)
        # Don't clobber a good cached list with an empty one from a transient LLM
        # blip — only write when we actually produced suggestions.
        if not suggestions:
            log.info(
                "[poll_suggest] no suggestions generated for user=%s group=%s (skip write)",
                user_id,
                group_id,
            )
            return
        with get_db() as conn:
            store_suggestions(conn, user_id, group_id, suggestions)
        log.info(
            "[poll_suggest] cached %d suggestions for user=%s group=%s",
            len(suggestions),
            user_id,
            group_id,
        )
    except Exception as exc:  # noqa: BLE001 — best-effort background work
        log.warning("[poll_suggest] refresh failed for user=%s group=%s: %s", user_id, group_id, exc)
